package com.bookstore.bookstoreapi;

import org.springframework.data.jpa.repository.JpaRepository;
@Repository
public interface AuthorRepository<Author> extends JpaRepository<Author, Long> {

server.port=8081

}
